import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import type { EncounterView, ExpeditionType, ExpeditionView } from '@unlikelyland/contracts';
import { PrismaService } from '../common/prisma.service';
import { CharactersService } from '../characters/characters.service';
import { EncountersService } from '../encounters/encounters.service';
import { EXPEDITIONS } from '../engine/rules';

export interface StartExpeditionResult {
  expedition: ExpeditionView;
  encounter: EncounterView;
}

/**
 * Expedition lifecycle. Starting one charges stamina for the first step and
 * generates the opening encounter; subsequent steps are charged + generated by
 * the resolution service. Only one active expedition per character at a time.
 */
@Injectable()
export class ExpeditionsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly characters: CharactersService,
    private readonly encounters: EncountersService,
  ) {}

  /** The available expedition types with labels and costs (for the picker UI). */
  listTypes() {
    return (Object.keys(EXPEDITIONS) as ExpeditionType[]).map((type) => ({
      type,
      label: EXPEDITIONS[type].label,
      staminaPerStep: EXPEDITIONS[type].staminaPerStep,
      steps: EXPEDITIONS[type].steps,
    }));
  }

  async start(characterId: string, type: ExpeditionType): Promise<StartExpeditionResult> {
    const character = await this.prisma.character.findUniqueOrThrow({ where: { id: characterId } });
    if (character.isDead) throw new BadRequestException('You are downed — revive first');

    const active = await this.prisma.expedition.findFirst({ where: { characterId, status: 'active' } });
    if (active) throw new BadRequestException('Finish or go home from your current expedition first');

    const cfg = EXPEDITIONS[type];

    // Charge stamina for step 1 and create the expedition atomically.
    const expedition = await this.prisma.$transaction(async (tx) => {
      await this.characters.consumeStamina(tx, characterId, cfg.staminaPerStep);
      return tx.expedition.create({
        data: {
          characterId,
          type,
          status: 'active',
          step: 0,
          maxSteps: cfg.steps,
          staminaPerStep: cfg.staminaPerStep,
        },
      });
    });

    // Generate the opening encounter (may call the AI provider) outside the tx.
    const encounter = await this.encounters.generateForStep(characterId, expedition.id, 1);

    return { expedition: this.toView(expedition), encounter };
  }

  async getActive(characterId: string): Promise<{ expedition: ExpeditionView | null; encounter: EncounterView | null }> {
    const expedition = await this.prisma.expedition.findFirst({
      where: { characterId, status: 'active' },
      orderBy: { startedAt: 'desc' },
    });
    if (!expedition) return { expedition: null, encounter: null };
    const encounter = await this.encounters.currentEncounterView(characterId);
    return { expedition: this.toView(expedition), encounter };
  }

  /**
   * Go home — allowed only when the server agrees it makes narrative sense: the
   * current unresolved encounter must offer it (or there is none). Ends the
   * expedition as abandoned with partial progress preserved.
   */
  async goHome(characterId: string, expeditionId: string): Promise<{ expedition: ExpeditionView }> {
    const expedition = await this.prisma.expedition.findUnique({ where: { id: expeditionId } });
    if (!expedition || expedition.characterId !== characterId) throw new NotFoundException('Expedition not found');
    if (expedition.status !== 'active') throw new BadRequestException('Expedition is not active');

    const current = await this.encounters.currentEncounterView(characterId);
    if (current && !current.allowGoHome) {
      throw new BadRequestException('You cannot simply leave right now');
    }

    const updated = await this.prisma.expedition.update({
      where: { id: expeditionId },
      data: { status: 'abandoned', endedAt: new Date(), summary: 'Decided home was the better option.' },
    });
    return { expedition: this.toView(updated) };
  }

  private toView(e: {
    id: string;
    type: string;
    status: string;
    step: number;
    maxSteps: number;
    staminaPerStep: number;
    startedAt: Date;
    endedAt: Date | null;
    summary: string | null;
  }): ExpeditionView {
    return {
      id: e.id,
      type: e.type as ExpeditionType,
      status: e.status as 'active' | 'completed' | 'abandoned' | 'failed',
      step: e.step,
      maxSteps: e.maxSteps,
      staminaPerStep: e.staminaPerStep,
      startedAt: e.startedAt.toISOString(),
      endedAt: e.endedAt ? e.endedAt.toISOString() : null,
      summary: e.summary,
    };
  }
}
