import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { AdvanceExpeditionView, EncounterView, ExpeditionType, ExpeditionView } from '@unlikelyland/contracts';
import { PrismaService } from '../common/prisma.service';
import { CharactersService } from '../characters/characters.service';
import { EncountersService } from '../encounters/encounters.service';
import { pickLocation } from '../content/locations';
import { EXPEDITIONS } from '../engine/rules';

export interface StartExpeditionResult {
  expedition: ExpeditionView;
  encounter: EncounterView;
}

/**
 * Expedition lifecycle. Starting one charges stamina for the first step and
 * generates the opening encounter; subsequent steps are charged + generated by
 * the resolution service. Only one active expedition per character at a time.
 */
@Injectable()
export class ExpeditionsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly characters: CharactersService,
    private readonly encounters: EncountersService,
  ) {}

  /** The available expedition types with labels and costs (for the picker UI). */
  listTypes() {
    return (Object.keys(EXPEDITIONS) as ExpeditionType[])
      .filter((type) => EXPEDITIONS[type].selectable)
      .map((type) => {
        const e = EXPEDITIONS[type];
        return {
          type,
          label: e.label,
          description: e.description,
          icon: e.icon,
          specialty: e.specialty,
          rewardHint: e.rewardHint,
          accent: e.accent,
          staminaPerStep: e.staminaPerStep,
          steps: e.steps,
        };
      });
  }

  async start(characterId: string, type: ExpeditionType): Promise<StartExpeditionResult> {
    const character = await this.prisma.character.findUniqueOrThrow({
      where: { id: characterId },
      include: { regionSet: true },
    });
    if (character.isDead) throw new BadRequestException('You are downed — revive first');

    const active = await this.prisma.expedition.findFirst({ where: { characterId, status: 'active' } });
    if (active) throw new BadRequestException('Finish or go home from your current expedition first');

    const cfg = EXPEDITIONS[type];
    if (!cfg?.selectable) throw new BadRequestException('That expedition is not available.');

    // Lock ONE named location for the whole expedition (from the hardcoded catalog,
    // biased toward the chosen activity) and resolve its premise/goal once, so every
    // step shares a single place and through-line. Fall back to a seeded region only
    // if this region set has no catalog entry.
    const picked = pickLocation(character.regionSet?.key, type);
    let regionName = picked?.name ?? '';
    if (!regionName) {
      const regions = await this.prisma.region.findMany({
        where: { regionSetId: character.regionSetId },
        select: { name: true },
      });
      regionName = regions.length ? regions[Math.floor(Math.random() * regions.length)].name : '';
    }
    const place = regionName || 'the island';
    const premise = cfg.premise.replace(/\{region\}/g, place);
    const goal = cfg.goal.replace(/\{region\}/g, place);

    // Charge stamina for step 1 and create the expedition atomically.
    const expedition = await this.prisma.$transaction(async (tx) => {
      await this.characters.consumeStamina(tx, characterId, cfg.staminaPerStep);
      return tx.expedition.create({
        data: {
          characterId,
          type,
          status: 'active',
          step: 0,
          maxSteps: cfg.steps,
          staminaPerStep: cfg.staminaPerStep,
          premise,
          goal,
          regionName: regionName || null,
        },
      });
    });

    // Generate the opening encounter (may call the AI provider) outside the tx.
    const encounter = await this.encounters.generateForStep(characterId, expedition.id, 1);

    return { expedition: this.toView(expedition), encounter };
  }

  async getActive(characterId: string): Promise<{ expedition: ExpeditionView | null; encounter: EncounterView | null }> {
    const expedition = await this.prisma.expedition.findFirst({
      where: { characterId, status: 'active' },
      orderBy: { startedAt: 'desc' },
    });
    if (!expedition) return { expedition: null, encounter: null };
    const encounter = await this.encounters.currentEncounterView(characterId);
    return { expedition: this.toView(expedition), encounter };
  }

  /**
   * Advance to the next step: charge stamina and generate the next encounter.
   * Split out of `resolve` so the player sees their outcome immediately while this
   * (potentially slow AI) call runs in the background.
   *
   * Idempotent: if an unresolved encounter already exists (prefetch + reload, a
   * double-tap), it is returned as-is without charging stamina or regenerating —
   * so calling this more than once per step is safe.
   */
  async advanceStep(characterId: string, expeditionId: string): Promise<AdvanceExpeditionView> {
    const expedition = await this.prisma.expedition.findUnique({ where: { id: expeditionId } });
    if (!expedition || expedition.characterId !== characterId) throw new NotFoundException('Expedition not found');

    // Idempotent fast path, scoped to THIS expedition so a dangling encounter from a
    // different (e.g. abandoned) run can never be served as this expedition's step.
    const existing = await this.encounters.currentEncounterForExpedition(characterId, expeditionId);
    if (existing) return { expedition: this.toView(expedition), encounter: existing };

    if (expedition.status !== 'active') return { expedition: this.toView(expedition), encounter: null };

    const stepIndex = expedition.step + 1;

    // Generate the (slow) content with NO DB writes, then charge stamina AND persist
    // the encounter in ONE transaction. The encounter's deterministic clientRequestId
    // means a concurrent advance for the same step hits the unique constraint and the
    // whole tx — the stamina charge included — rolls back. So two overlapping advances
    // can never double-charge or create two encounters for one step.
    const content = await this.encounters.generateStepContent(characterId, expeditionId, stepIndex);

    let encounter: EncounterView;
    try {
      encounter = await this.prisma.$transaction(async (tx) => {
        await this.characters.consumeStamina(tx, characterId, expedition.staminaPerStep);
        return this.encounters.createStepEncounter(tx, characterId, expeditionId, stepIndex, content);
      });
    } catch (err) {
      // Lost the race to a concurrent advance: return the encounter it committed.
      if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === 'P2002') {
        const winner = await this.encounters.currentEncounterForExpedition(characterId, expeditionId);
        return { expedition: this.toView(expedition), encounter: winner };
      }
      // Not enough stamina: the expedition ends early, without the completion bonus.
      if (err instanceof BadRequestException) {
        const ended = await this.prisma.expedition.update({
          where: { id: expeditionId },
          data: { status: 'completed', endedAt: new Date(), summary: 'Ran out of steam and headed back.' },
        });
        return { expedition: this.toView(ended), encounter: null };
      }
      throw err;
    }

    // Item-concept ingestion is best-effort and runs after the encounter is committed.
    await this.encounters.ingestStepConcepts(characterId, content.encounter.itemConceptSuggestions);
    return { expedition: this.toView(expedition), encounter };
  }

  /**
   * Go home — allowed only when the server agrees it makes narrative sense: the
   * current unresolved encounter must offer it (or there is none). Ends the
   * expedition as abandoned with partial progress preserved.
   */
  async goHome(characterId: string, expeditionId: string): Promise<{ expedition: ExpeditionView }> {
    const expedition = await this.prisma.expedition.findUnique({ where: { id: expeditionId } });
    if (!expedition || expedition.characterId !== characterId) throw new NotFoundException('Expedition not found');
    if (expedition.status !== 'active') throw new BadRequestException('Expedition is not active');

    const current = await this.encounters.currentEncounterView(characterId);
    if (current && !current.allowGoHome) {
      throw new BadRequestException('You cannot simply leave right now');
    }

    // Abandon the expedition AND resolve any leftover unresolved encounter in one
    // transaction, so it can't linger and leak into a later run (mirrors prestige).
    const updated = await this.prisma.$transaction(async (tx) => {
      const exp = await tx.expedition.update({
        where: { id: expeditionId },
        data: { status: 'abandoned', endedAt: new Date(), summary: 'Decided home was the better option.' },
      });
      await tx.encounter.updateMany({
        where: { characterId, resolved: false },
        data: { resolved: true, resolvedAt: new Date() },
      });
      return exp;
    });
    return { expedition: this.toView(updated) };
  }

  private toView(e: {
    id: string;
    type: string;
    status: string;
    step: number;
    maxSteps: number;
    staminaPerStep: number;
    premise?: string | null;
    goal?: string | null;
    regionName?: string | null;
    startedAt: Date;
    endedAt: Date | null;
    summary: string | null;
  }): ExpeditionView {
    return {
      id: e.id,
      type: e.type as ExpeditionType,
      status: e.status as 'active' | 'completed' | 'abandoned' | 'failed',
      step: e.step,
      maxSteps: e.maxSteps,
      staminaPerStep: e.staminaPerStep,
      premise: e.premise ?? null,
      goal: e.goal ?? null,
      regionName: e.regionName ?? null,
      startedAt: e.startedAt.toISOString(),
      endedAt: e.endedAt ? e.endedAt.toISOString() : null,
      summary: e.summary,
    };
  }
}
