import {
  BadRequestException,
  ConflictException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import {
  categoryForStat,
  type CurrencyType,
  type Encounter,
  type EncounterChoice,
  type Rarity,
  type ResolutionView,
  type ResolveChoiceInput,
  type RewardView,
  type StatNudgeView,
} from '@unlikelyland/contracts';
import { PrismaService } from '../common/prisma.service';
import { CharactersService } from '../characters/characters.service';
import { EconomyService } from '../economy/economy.service';
import { LootService } from '../economy/loot.service';
import { StoryMemoryService } from '../story-memory/story-memory.service';
import { EncountersService } from './encounters.service';
import { AchievementsService } from '../achievements/achievements.service';
import { rngFor } from '../engine/rng';
import { resolveCheck } from '../engine/checks';
import { makeEnemy, makePlayerCombatant, resolveCombat, type CombatResult } from '../engine/combat';
import { computeReward, expeditionCompletionReward } from '../engine/rewards';
import { buildOutcomeNarrative, buildOutcomeSummary } from '../engine/outcome-text';
import { levelFromXp } from '../engine/leveling';
import { DEATH, PERSONALITY, PERSONALITY_FOCUS } from '../engine/rules';
import type { ExpeditionType } from '@unlikelyland/contracts';

/** Static outcome portion stored on the encounter for idempotent replay. */
interface ResolutionSnapshot {
  narrative: string;
  check: ResolutionView['check'];
  combat: ResolutionView['combat'];
  rewards: RewardView;
  statNudges: StatNudgeView[];
  died: boolean;
  deathReason: string | null;
}

/**
 * The heart of the game loop: turn a chosen option into a validated outcome,
 * atomically. Server-authoritative throughout — the AI/client never supply
 * rewards or stat changes. Resolution is idempotent (a duplicate submit with the
 * same clientRequestId replays the stored outcome) and race-safe (the encounter
 * is claimed with a conditional update inside the transaction).
 *
 * Resolve never calls the AI provider itself: the next encounter is generated by a
 * separate POST /expeditions/advance request, so the outcome returns immediately.
 */
@Injectable()
export class ResolutionService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly characters: CharactersService,
    private readonly economy: EconomyService,
    private readonly loot: LootService,
    private readonly memory: StoryMemoryService,
    private readonly encounters: EncountersService,
    private readonly achievements: AchievementsService,
  ) {}

  async resolve(characterId: string, dto: ResolveChoiceInput): Promise<ResolutionView> {
    const encounter = await this.prisma.encounter.findUnique({ where: { id: dto.encounterId } });
    if (!encounter || encounter.characterId !== characterId) {
      throw new NotFoundException('Encounter not found');
    }

    // Idempotent replay / double-submit guard.
    if (encounter.resolved) {
      if (dto.clientRequestId && encounter.clientRequestId === dto.clientRequestId && encounter.resolution) {
        return this.rebuildView(characterId, encounter.id, encounter.resolution as unknown as ResolutionSnapshot, encounter.expeditionId);
      }
      throw new ConflictException('This encounter was already resolved');
    }

    const character = await this.prisma.character.findUniqueOrThrow({
      where: { id: characterId },
      include: { stats: true },
    });
    if (character.isDead) {
      throw new BadRequestException('You are downed — revive before continuing');
    }

    // A dangling encounter can point at an expedition that is no longer active (e.g.
    // one abandoned via go-home). Refuse to resolve it, so it can't resurrect a
    // terminal expedition, re-pay its completion bonus, or grant rewards out of band.
    if (encounter.expeditionId) {
      const exp = await this.prisma.expedition.findUnique({
        where: { id: encounter.expeditionId },
        select: { status: true },
      });
      if (!exp || exp.status !== 'active') {
        throw new BadRequestException('This expedition is no longer active');
      }
    }

    const payload = encounter.payload as Encounter;
    const choice = payload.choices.find((c) => c.id === dto.choiceId);
    if (!choice) throw new BadRequestException('Unknown choice for this encounter');

    // Effective stats include equipped-item modifiers.
    const stats = await this.characters.getEffectiveStats(characterId);
    const level = levelFromXp(character.xp).level;
    const rng = rngFor(encounter.id, choice.id);

    // 1. Stat check.
    const statValue = stats[choice.statFocus];
    const check = resolveCheck(statValue, level, stats.weirdness, choice.riskLevel, rng);

    // 2. Optional combat.
    let combat: CombatResult | null = null;
    if (choice.mayStartCombat) {
      const enemyName = this.enemyName(payload);
      const enemy = makeEnemy(enemyName, level, choice.riskLevel);
      const player = makePlayerCombatant(stats, level);
      combat = resolveCombat(player, enemy, rng);
    }

    // 3. Death — losing a fight downs you; a ridiculous fumble can also be fatal.
    let died = false;
    let deathReason: string | null = null;
    if (combat && !combat.playerWon) {
      died = true;
      deathReason = `Bested by ${combat.enemyName}`;
    } else if (!combat && check.fumble && choice.riskLevel === 'ridiculous' && rng.chance(0.25)) {
      died = true;
      deathReason = 'A ridiculous idea, pursued to its natural conclusion';
    }

    // 4. Rewards (none on death). Combat success overrides the stat check for
    //    reward purposes; otherwise the check decides.
    const rewardSuccess = combat ? combat.playerWon : check.success;
    const reward = died
      ? { xp: 0, normal: 0, crafting: 0, reputation: 0, premium: 0, itemDrop: null }
      : computeReward({
          riskLevel: choice.riskLevel,
          rewardProfile: choice.rewardProfile,
          encounterType: payload.encounterType,
          success: rewardSuccess,
          margin: check.margin,
          level,
          rng,
        });

    // 5. Personality drift.
    const statNudges = this.computePersonalityNudges(choice);

    // 6. Resolve an item drop against the approved catalog via the centralized
    //    loot service (read before the tx; the grant + audit happen inside it).
    //    Drop selection is biased by the expedition type when there is one.
    const expeditionType = await this.expeditionTypeFor(encounter.expeditionId);
    const droppedItem = reward.itemDrop
      ? await this.loot.pickDrop({ rarity: reward.itemDrop.rarity, expeditionType, level, rng })
      : null;

    // 7. Narrative (engine fallback text — deterministic, on-tone).
    const narrative = buildOutcomeNarrative({ choice, check, combat, died }, rng);

    const rewardView: RewardView = {
      xp: reward.xp,
      currencies: this.rewardCurrencies(reward),
      items: droppedItem ? [{ name: droppedItem.name, rarity: droppedItem.rarity as never, slot: droppedItem.slot as never }] : [],
    };

    const snapshot: ResolutionSnapshot = {
      narrative,
      check: {
        statFocus: choice.statFocus,
        statValue,
        difficulty: check.difficulty,
        roll: check.roll,
        total: check.total,
        success: check.success,
        margin: check.margin,
      },
      combat: combat
        ? {
            enemyName: combat.enemyName,
            playerMaxHp: combat.playerMaxHp,
            enemyMaxHp: combat.enemyMaxHp,
            rounds: combat.rounds,
            playerWon: combat.playerWon,
            playerHpRemaining: combat.playerHpRemaining,
          }
        : null,
      rewards: rewardView,
      statNudges,
      died,
      deathReason,
    };

    // 8. Commit everything atomically.
    let expeditionCompleted = false;
    let completionBonus: RewardView | null = null;

    await this.prisma.$transaction(async (tx) => {
      // Claim the encounter — conditional update prevents a concurrent double-resolve.
      const claim = await tx.encounter.updateMany({
        where: { id: encounter.id, characterId, resolved: false },
        data: {
          resolved: true,
          resolvedChoiceId: choice.id,
          resolvedAt: new Date(),
          clientRequestId: dto.clientRequestId ?? undefined,
          resolution: snapshot as unknown as Prisma.InputJsonValue,
        },
      });
      if (claim.count === 0) throw new ConflictException('This encounter was already resolved');

      // Rewards.
      if (!died) {
        await this.economy.applyDeltas(
          tx,
          characterId,
          { xp: reward.xp, normal: reward.normal, crafting: reward.crafting, reputation: reward.reputation },
          `encounter:${choice.id}`,
          encounter.id,
        );
      }

      // Personality drift, clamped to the documented 0..100 ceiling: the conditional
      // updateMany only increments while the stat is still low enough that the bump
      // won't exceed 100, so repeated play can't drift a personality stat past the cap.
      for (const nudge of statNudges) {
        await tx.characterStats.updateMany({
          where: { characterId, [nudge.stat]: { lte: 100 - nudge.delta } },
          data: { [nudge.stat]: { increment: nudge.delta } },
        });
      }

      // Item grant — created and audited inside the same claim transaction, so a
      // replayed/duplicate submit (which never re-enters this block) can't grant
      // the item twice.
      if (droppedItem) {
        await tx.inventoryItem.create({
          data: { characterId, itemDefinitionId: droppedItem.id, quantity: 1 },
        });
        await this.economy.logItemReward(tx, characterId, droppedItem.id, 1, `encounter:${choice.id}`, encounter.id);
      }

      // Death.
      if (died) {
        const waitMs = Math.min(
          DEATH.MAX_WAIT_MS,
          DEATH.BASE_WAIT_MS * (1 + character.deathCount * DEATH.WAIT_GROWTH_PER_DEATH),
        );
        const freeRevive = rng.chance(DEATH.FREE_REVIVE_CHANCE);
        await tx.character.update({
          where: { id: characterId },
          data: {
            isDead: true,
            deathStartedAt: new Date(),
            reviveAvailableAt: new Date(Date.now() + waitMs),
            deathReason,
            deathCount: { increment: 1 },
            freeReviveAvailable: freeRevive,
          },
        });
        await tx.deathRecord.create({
          data: { characterId, reason: deathReason ?? 'unknown', freeReviveAvailable: freeRevive },
        });
      }

      // Story memory.
      await this.memory.recordDecision(tx, characterId, buildOutcomeSummary({ choice, check, combat }), character.regionSetId);
      await this.memory.recordSuggestions(tx, characterId, payload.memorySuggestions, character.regionSetId);
      await this.memory.upsertNpcs(tx, characterId, payload.npcSuggestions, character.regionSetId);

      // Combat-victory counter (server-authoritative; feeds the leaderboard).
      if (combat?.playerWon) {
        await tx.character.update({ where: { id: characterId }, data: { combatVictories: { increment: 1 } } });
      }

      // Public achievements + activity feed via the central evaluator (idempotent).
      const oldLevel = levelFromXp(character.xp).level;
      const newLevel = died ? oldLevel : levelFromXp(character.xp + reward.xp).level;
      await this.achievements.evaluateEncounter(tx, characterId, {
        died,
        riskLevel: choice.riskLevel,
        wonCombat: combat ? combat.playerWon : null,
        oldLevel,
        newLevel,
        droppedRarity: droppedItem ? (droppedItem.rarity as Rarity) : null,
      });

      // Expedition advancement (terminal states only; next encounter is generated
      // outside the transaction because it may call the AI provider).
      if (encounter.expeditionId) {
        const expedition = await tx.expedition.findUniqueOrThrow({ where: { id: encounter.expeditionId } });
        const newStep = expedition.step + 1;
        if (died) {
          await tx.expedition.update({
            where: { id: expedition.id },
            data: { step: newStep, status: 'failed', endedAt: new Date(), summary: deathReason },
          });
        } else if (newStep >= expedition.maxSteps) {
          const bonus = expeditionCompletionReward(expedition.maxSteps);
          await this.economy.applyDeltas(tx, characterId, { xp: bonus.xp, normal: bonus.normal }, 'expedition:complete', expedition.id);
          await tx.expedition.update({
            where: { id: expedition.id },
            data: { step: newStep, status: 'completed', endedAt: new Date(), summary: 'Made it through in one piece.' },
          });
          expeditionCompleted = true;
          completionBonus = { xp: bonus.xp, currencies: { normal: bonus.normal }, items: [] };
        } else {
          await tx.expedition.update({ where: { id: expedition.id }, data: { step: newStep } });
        }
      }
    });

    // 9. The next encounter is intentionally NOT generated here. Resolve returns the
    //    outcome immediately and the client calls POST /expeditions/advance to
    //    generate the next step in the background, hidden behind the time the player
    //    spends reading this outcome. `nextStepPending` tells the client to do that.
    const nextStepPending = !!encounter.expeditionId && !died && !expeditionCompleted;

    // Best-effort memory compaction (keeps Story Memory bounded; never blocks).
    await this.memory.compactIfNeeded(characterId).catch(() => undefined);

    const characterView = await this.characters.buildView(characterId);
    const expeditionView = encounter.expeditionId ? await this.expeditionView(encounter.expeditionId) : null;

    return {
      encounterId: encounter.id,
      choiceId: choice.id,
      narrative: snapshot.narrative,
      check: snapshot.check,
      combat: snapshot.combat,
      rewards: snapshot.rewards,
      statNudges: snapshot.statNudges,
      died,
      deathReason,
      expeditionCompleted,
      completionBonus,
      character: characterView,
      expedition: expeditionView,
      nextEncounter: null,
      nextStepPending,
    };
  }

  private computePersonalityNudges(choice: EncounterChoice): StatNudgeView[] {
    if (!PERSONALITY_FOCUS.has(choice.statFocus)) return [];
    const delta = choice.riskLevel === 'ridiculous' ? PERSONALITY.NUDGE_BIG : PERSONALITY.NUDGE;
    return [{ stat: choice.statFocus, statLabel: this.characters.statLabel(choice.statFocus), delta }];
  }

  private rewardCurrencies(reward: { normal: number; crafting: number; reputation: number; premium: number }): Partial<Record<CurrencyType, number>> {
    const out: Partial<Record<CurrencyType, number>> = {};
    if (reward.normal) out.normal = reward.normal;
    if (reward.crafting) out.crafting = reward.crafting;
    if (reward.reputation) out.reputation = reward.reputation;
    if (reward.premium) out.premium = reward.premium;
    return out;
  }

  private enemyName(payload: Encounter): string {
    const enemyNpc = payload.npcSuggestions.find((n) => /enemy|foe|beast|monster/i.test(n.role));
    if (enemyNpc) return enemyNpc.name;
    if (payload.npcSuggestions[0]) return payload.npcSuggestions[0].name;
    return payload.title;
  }

  /** Expedition type for loot bias, or null for one-off (non-expedition) encounters. */
  private async expeditionTypeFor(expeditionId: string | null): Promise<ExpeditionType | null> {
    if (!expeditionId) return null;
    const e = await this.prisma.expedition.findUnique({ where: { id: expeditionId }, select: { type: true } });
    return (e?.type as ExpeditionType) ?? null;
  }

  private async expeditionView(expeditionId: string) {
    const e = await this.prisma.expedition.findUniqueOrThrow({ where: { id: expeditionId } });
    return {
      id: e.id,
      type: e.type as ExpeditionType,
      status: e.status as 'active' | 'completed' | 'abandoned' | 'failed',
      step: e.step,
      maxSteps: e.maxSteps,
      staminaPerStep: e.staminaPerStep,
      premise: e.premise ?? null,
      goal: e.goal ?? null,
      regionName: e.regionName ?? null,
      startedAt: e.startedAt.toISOString(),
      endedAt: e.endedAt ? e.endedAt.toISOString() : null,
      summary: e.summary,
    };
  }

  /** Rebuild a full view from a stored snapshot for an idempotent replay. */
  private async rebuildView(
    characterId: string,
    encounterId: string,
    snapshot: ResolutionSnapshot,
    expeditionId: string | null,
  ): Promise<ResolutionView> {
    const character = await this.characters.buildView(characterId);
    const expedition = expeditionId ? await this.expeditionView(expeditionId) : null;
    const nextEncounter = await this.encounters.currentEncounterView(characterId);
    // Recompute the completion bonus on replay (it's a pure function of step count),
    // so a duplicate submit shows the same "+X XP" line the original response did.
    const completionBonus =
      expedition?.status === 'completed'
        ? (() => {
            const b = expeditionCompletionReward(expedition.maxSteps);
            return { xp: b.xp, currencies: { normal: b.normal }, items: [] };
          })()
        : null;
    return {
      encounterId,
      choiceId: '',
      narrative: snapshot.narrative,
      check: snapshot.check,
      combat: snapshot.combat,
      rewards: snapshot.rewards,
      statNudges: snapshot.statNudges,
      died: snapshot.died,
      deathReason: snapshot.deathReason,
      expeditionCompleted: expedition?.status === 'completed',
      completionBonus,
      character,
      expedition,
      nextEncounter,
      // If the expedition is still going and the next encounter hasn't been
      // generated yet, the client should still call advance.
      nextStepPending: !nextEncounter && expedition?.status === 'active' && !snapshot.died,
    };
  }
}
